# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idf_editor.ui'
#
# Created: Thu Dec 26 22:26:50 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listView = QtGui.QListView(self.splitter)
        self.listView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.tableView = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuObject = QtGui.QMenu(self.menuEdit)
        self.menuObject.setObjectName("menuObject")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/16x16/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/16x16/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon1)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/16x16/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionShowClassesWithObjectsOnly = QtGui.QAction(MainWindow)
        self.actionShowClassesWithObjectsOnly.setCheckable(True)
        self.actionShowClassesWithObjectsOnly.setObjectName("actionShowClassesWithObjectsOnly")
        self.actionNewObject = QtGui.QAction(MainWindow)
        self.actionNewObject.setObjectName("actionNewObject")
        self.actionDeleteObject = QtGui.QAction(MainWindow)
        self.actionDeleteObject.setObjectName("actionDeleteObject")
        self.actionCopyObject = QtGui.QAction(MainWindow)
        self.actionCopyObject.setObjectName("actionCopyObject")
        self.actionDuplicateObject = QtGui.QAction(MainWindow)
        self.actionDuplicateObject.setObjectName("actionDuplicateObject")
        self.actionPasteObject = QtGui.QAction(MainWindow)
        self.actionPasteObject.setObjectName("actionPasteObject")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.actionShowClassesWithObjectsOnly)
        self.menuObject.addAction(self.actionNewObject)
        self.menuObject.addAction(self.actionDuplicateObject)
        self.menuObject.addAction(self.actionDeleteObject)
        self.menuObject.addAction(self.actionCopyObject)
        self.menuObject.addAction(self.actionPasteObject)
        self.menuEdit.addAction(self.menuObject.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionNewObject)
        self.toolBar.addAction(self.actionDuplicateObject)
        self.toolBar.addAction(self.actionDeleteObject)
        self.toolBar.addAction(self.actionCopyObject)
        self.toolBar.addAction(self.actionPasteObject)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuObject.setTitle(QtGui.QApplication.translate("MainWindow", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowClassesWithObjectsOnly.setText(QtGui.QApplication.translate("MainWindow", "Show Classes with Objects Only", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowClassesWithObjectsOnly.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewObject.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewObject.setIconText(QtGui.QApplication.translate("MainWindow", "New Obj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewObject.setToolTip(QtGui.QApplication.translate("MainWindow", "New Object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewObject.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteObject.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteObject.setIconText(QtGui.QApplication.translate("MainWindow", "Del Obj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteObject.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete Object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopyObject.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopyObject.setIconText(QtGui.QApplication.translate("MainWindow", "Copy Obj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopyObject.setToolTip(QtGui.QApplication.translate("MainWindow", "Copy Object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateObject.setText(QtGui.QApplication.translate("MainWindow", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateObject.setIconText(QtGui.QApplication.translate("MainWindow", "Dup Obj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateObject.setToolTip(QtGui.QApplication.translate("MainWindow", "Duplicate Object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasteObject.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasteObject.setIconText(QtGui.QApplication.translate("MainWindow", "Paste Obj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasteObject.setToolTip(QtGui.QApplication.translate("MainWindow", "Paste Object", None, QtGui.QApplication.UnicodeUTF8))

import idf_editor_rc
